### ISSUE TITLE
It doesn't work like the README says

### ISSUE THREAD

**Issue by miskolc** [tuvistavie/phoenix-active-link#1]
If I use `active_link` by it's own I get `undefined function active_link/3`.
However it works if I specify the mondule name `PhoenixActiveLink.active_link`.
Is there any missing step?

**Comment by danhper** [comment]
Hi, thanks for reporting.
I indeed forgot to mention the step where you need to import the module.
I just updated the README!

**Comment by miskolc** [comment]
I suspected an import was needed unfortunately I though it should have been done in the View Module and not in `web.ex`. 
I've tried your solution now and it works.

**Comment by danhper** [comment]
It can also be done in the view module, but in this case it must be done in the module that actually renders the part of your page where you use the `active_link` function.
I usually simply add it to `web.ex`.
