### ISSUE TITLE
Font Awesome and Bootstrap 4 Links / Navbar

### ISSUE THREAD

**Issue by taorg** [tuvistavie/phoenix-active-link#11]
It would be nice to be able to add icons, Font Awesome or whatever other lib to links.
This is an example with Navbar, valid for links to
https://stackoverflow.com/questions/35005960/font-awesome-and-bootstrap-4-navbar

**Comment by chrism2671** [comment]
It is possible:
`<%= active_link(@conn, "<i class=\"fa fa-th-large\"></i>Create New Link" |> raw, to: "/links/new", wrap_tag: :li) %>`

**Comment by danhper** [comment]
Sorry for the delay.
This should be doable with the following

```erb
    <%= active_link(@conn, to: "/links/new") do %>
     <i class="fa fa-th-large"></i>Create New Link
    <% end %>
```

Please comment if this does not work.
