### ISSUE TITLE
Cannot deps.get

### ISSUE THREAD

**Issue by arnimikelsons** [tuvistavie/phoenix-active-link#21]
Trying to install, but getting this error: 

Failed to use "phoenix_html" (version 3.2.0) because
  phoenix_active_link (version 0.2.1) requires ~> 2.10
  phoenix_ecto (version 4.4.0) requires ~> 2.14.2 or ~> 3.0
  phoenix_live_view (version 0.17.9) requires ~> 3.1
  mix.lock specifies 3.2.0

running phoenix 1.6.7

**Comment by Matsa59** [comment]
Hello sorry github didn't notify me for your issue ...
What version of `phoenix_active_link` are you using? We released version `0.3.2` that fixed  the problem
